- hosts: kube-master

  vars:
    prom_ns: "monitoring"
    # https://hub.docker.com/r/prom/prometheus/tags/
    prom_image: "prom/prometheus:v1.5.2"
    # https://hub.docker.com/r/prom/node-exporter/tags/
    prom_node_exported_image: "prom/node-exporter:v0.14.0-rc.2"
    # Settings
    storage_local_retention: "720h"

  tasks:

    - name: Get svc
      shell: kubectl --namespace={{ prom_ns }} get svc
      register: get_svc
      run_once: true

    - name: Get ns
      shell: kubectl get ns
      register: get_ns
      run_once: true

    - name: Upload files
      copy:
        src: "{{ item }}"
        dest: "/var/tmp/{{ item }}"
      run_once: true
      with_items:
        - "prometheus-rules.yaml"
      when: get_svc.stdout.find('prometheus') == -1

    - name: Upload templates
      template: src=./{{ item }}.j2 dest=/var/tmp/{{ item }}
      run_once: true
      with_items:
        - "prometheus-node-exporter.yaml"
        - "prometheus-configmap.yaml"
        - "prometheus-deployment.yaml"
      when: get_svc.stdout.find('prometheus') == -1

    - name: Create namespace
      shell: kubectl create namespace {{ prom_ns }}
      run_once: true
      when: get_ns.stdout.find('{{ prom_ns }}') == -1

    - name: Deploy prometheus
      shell: kubectl --namespace={{ prom_ns }} create -f /var/tmp/{{ item }}
      run_once: true
      with_items:
        - "prometheus-node-exporter.yaml"
        - "prometheus-configmap.yaml"
        - "prometheus-rules.yaml"
        - "prometheus-deployment.yaml"
      when: get_svc.stdout.find('prometheus') == -1
